application: antplanner
version: release-0-9-8-1
api_version: 1
runtime: python
 
handlers:
- url: /static
  static_dir: static
- url: /admin.*
  script: antplanner.py
  login: admin
- url: .*
  script: antplanner.py